# Generated by Django 5.2.6 on 2025-09-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='8', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
    ]
