# Generated by Django 5.2.6 on 2025-09-07 10:02

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=1, editable=False, max_length=22, unique=True),
            preserve_default=False,
        ),
    ]
