# Generated by Django 5.2.6 on 2025-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skue',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
