# Generated by Django 5.2.6 on 2025-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_skue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skue',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
