# Generated by Django 5.2.6 on 2025-09-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ ☆☆☆☆'), (2, '⭐ ⭐ ☆☆☆'), (3, '⭐ ⭐ ⭐ ☆☆'), (4, '⭐ ⭐ ⭐ ⭐ ☆'), (5, '⭐ ⭐ ⭐ ⭐ ⭐')], default=3),
        ),
    ]
