# Generated by Django 5.2.6 on 2025-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_productreviews_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
