# Generated by Django 5.2.6 on 2025-09-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
