# Generated by Django 5.2.6 on 2025-09-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cartorderitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
