# Generated by Django 5.2.6 on 2025-09-30 06:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
