# Generated by Django 5.2.6 on 2025-10-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
